FROM adoptopenjdk/openjdk11:alpine as builder
RUN apk update && \
    apk add bash curl --no-cache
WORKDIR /app/ms-associados
COPY . .
ENV LANG en_US.utf8
VOLUME /tmp
VOLUME /app/logs
VOLUME /app/config
RUN ls -la /app/ms-associados
RUN chmod +x /app/ms-associados/dev-docker-entrypoint.sh
RUN ls -la /app/ms-associados
EXPOSE 8090
ENTRYPOINT ["/app/ms-associados/dev-docker-entrypoint.sh"]